apiVersion: apps/v1
kind: Deployment
metadata:
  name: reward
  labels:
    app: reward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reward
  template:
    metadata:
      labels:
        app: reward
    spec:
      containers:
        - name: reward
          image: username/reward:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5